services:
  server:
    build: 
      context: .
      # run up to production stage
      target: production
    environment:
      NODE_ENV: production
    ports:
      - 4000:3000 # web server port
    volumes:
      - ./data:/usr/src/app/data